pipeline:
    name: test
    identifier: test
    allowStageExecutions: false
    projectIdentifier: Jordi
    orgIdentifier: default
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: account.Nofar_Github
                repoName: gitExpTest1
                build: <+input>
    stages:
        - stage:
              name: S1
              identifier: S1
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: account.k8scluster
                          namespace: harness-delegate-pmdemo
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: echo
                                identifier: echo
                                spec:
                                    connectorRef: account.nofar_dockerhub
                                    image: alpine
                                    command: echo "hello"
